"""initial schema

Revision ID: ab0185d63d95
Revises: 
Create Date: 2026-02-07 22:39:53.555067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab0185d63d95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('delivery_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PREPARING', 'DELIVERING', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'TRANSFER', name='paymentmethod'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_index(op.f('ix_order_client_id'), 'order', ['client_id'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_table('orderdetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderdetail_order_id'), 'orderdetail', ['order_id'], unique=False)
    op.create_index(op.f('ix_orderdetail_product_id'), 'orderdetail', ['product_id'], unique=False)
    op.create_table('productvariant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productvariant_product_id'), 'productvariant', ['product_id'], unique=False)
    # ### end Alembic commands ###

    # ── Triggers ─────────────────────────────────
    # Trigger 1: Calcular subtotal del detalle y recalcular total de la orden
    op.execute("""
        CREATE OR REPLACE FUNCTION fn_calcular_totales()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.subtotal := NEW.unit_price * NEW.quantity;

            UPDATE "order"
            SET total = COALESCE(
                (SELECT SUM(subtotal) FROM orderdetail WHERE order_id = NEW.order_id AND id != NEW.id), 0
            ) + NEW.subtotal
            WHERE id = NEW.order_id;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER trg_calcular_totales
        BEFORE INSERT OR UPDATE ON orderdetail
        FOR EACH ROW
        EXECUTE FUNCTION fn_calcular_totales();
    """)

    # Trigger 2: Cambiar estado del pedido según estado del pago
    op.execute("""
        CREATE OR REPLACE FUNCTION fn_estado_segun_pago()
        RETURNS TRIGGER AS $$
        BEGIN
            IF OLD.payment_status IS DISTINCT FROM NEW.payment_status THEN
                IF NEW.payment_status = 'PAID' AND NEW.status = 'PENDING' THEN
                    NEW.status := 'CONFIRMED';
                ELSIF NEW.payment_status = 'REFUNDED' THEN
                    NEW.status := 'CANCELLED';
                END IF;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER trg_estado_segun_pago
        BEFORE UPDATE ON "order"
        FOR EACH ROW
        EXECUTE FUNCTION fn_estado_segun_pago();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ── Drop triggers primero ────────────────────
    op.execute("DROP TRIGGER IF EXISTS trg_estado_segun_pago ON \"order\"")
    op.execute("DROP FUNCTION IF EXISTS fn_estado_segun_pago()")
    op.execute("DROP TRIGGER IF EXISTS trg_calcular_totales ON orderdetail")
    op.execute("DROP FUNCTION IF EXISTS fn_calcular_totales()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productvariant_product_id'), table_name='productvariant')
    op.drop_table('productvariant')
    op.drop_index(op.f('ix_orderdetail_product_id'), table_name='orderdetail')
    op.drop_index(op.f('ix_orderdetail_order_id'), table_name='orderdetail')
    op.drop_table('orderdetail')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_client_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_table('client')
    op.drop_table('category')
    # ### end Alembic commands ###

    # ── Drop enum types ──────────────────────────
    op.execute("DROP TYPE IF EXISTS role")
    op.execute("DROP TYPE IF EXISTS orderstatus")
    op.execute("DROP TYPE IF EXISTS paymentstatus")
    op.execute("DROP TYPE IF EXISTS paymentmethod")
