"""sin_tarjeta

Revision ID: b5c0e9ec4cbd
Revises: 0003
Create Date: 2026-04-06 11:54:56.564993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5c0e9ec4cbd'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_cake_request', 'additional_notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('custom_cake_request', 'admin_notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('ix_custom_cake_request_delivery_date'), table_name='custom_cake_request')
    op.drop_constraint(op.f('custom_cake_request_client_id_fkey'), 'custom_cake_request', type_='foreignkey')
    op.create_foreign_key(None, 'custom_cake_request', 'client', ['client_id'], ['id'])
    op.drop_index(op.f('ix_order_audit_action'), table_name='order_audit')
    op.drop_index(op.f('ix_order_audit_changed_at'), table_name='order_audit')
    op.drop_index(op.f('ix_orderdetail_order_id'), table_name='order_detail')
    op.drop_index(op.f('ix_orderdetail_product_id'), table_name='order_detail')
    op.create_index(op.f('ix_order_detail_order_id'), 'order_detail', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_detail_product_id'), 'order_detail', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_detail_product_id'), table_name='order_detail')
    op.drop_index(op.f('ix_order_detail_order_id'), table_name='order_detail')
    op.create_index(op.f('ix_orderdetail_product_id'), 'order_detail', ['product_id'], unique=False)
    op.create_index(op.f('ix_orderdetail_order_id'), 'order_detail', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_audit_changed_at'), 'order_audit', ['changed_at'], unique=False)
    op.create_index(op.f('ix_order_audit_action'), 'order_audit', ['action'], unique=False)
    op.drop_constraint(None, 'custom_cake_request', type_='foreignkey')
    op.create_foreign_key(op.f('custom_cake_request_client_id_fkey'), 'custom_cake_request', 'client', ['client_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_custom_cake_request_delivery_date'), 'custom_cake_request', ['delivery_date'], unique=False)
    op.alter_column('custom_cake_request', 'admin_notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('custom_cake_request', 'additional_notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
